## Some Common Terms To Remember:
    1. Corpus
    2. Vocabulary
    3. Document
    4. Word

## Bag Of Words - BOW

In [5]:
import numpy as np
import pandas as pd

In [21]:
df = pd.DataFrame({
    "text": [
        "people watch shwatech",
        "shwatech watch shwatech",
        "people write comment",
        "shwatech write comment"
    ],
    "output": [
        1,
        1,
        0,
        0
    ]
})

df

text  output
0    people watch shwatech       1
1  shwatech watch shwatech       1
2     people write comment       0
3   shwatech write comment       0

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [25]:
bow = cv.fit_transform(df['text'])

In [27]:
# Vocabulary ??
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'shwatech': 2, 'write': 4, 'comment': 0}


In [29]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 0, 2, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1]], dtype=int64)

In [31]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 1 1 1 0]]
[[0 0 2 1 0]]
[[1 1 0 0 1]]
[[1 0 1 0 1]]


In [33]:
X = bow.toarray()

y = df['output']

## N-grams

In [36]:
df = pd.DataFrame({
    "text": [
        "people watch shwatech",
        "shwatech watch shwatech",
        "people write comment",
        "shwatech write comment"
    ],
    "output": [
        1,
        1,
        0,
        0
    ]
})

df

text  output
0    people watch shwatech       1
1  shwatech watch shwatech       1
2     people write comment       0
3   shwatech write comment       0

In [56]:
from sklearn.feature_extraction.text import CountVectorizer

In [58]:
# BI Grams
BI_cv = CountVectorizer(ngram_range=(2, 2))

In [46]:
bow = BI_cv.fit_transform(df['text'])

In [48]:
print(BI_cv.vocabulary_)

{'people watch': 0, 'watch shwatech': 4, 'shwatech watch': 2, 'people write': 1, 'write comment': 5, 'shwatech write': 3}


In [50]:
# Tri Grams
Tri_cv = CountVectorizer(ngram_range=(3, 3))

In [52]:
bow = Tri_cv.fit_transform(df['text'])

In [54]:
print(Tri_cv.vocabulary_)

{'people watch shwatech': 0, 'shwatech watch shwatech': 2, 'people write comment': 1, 'shwatech write comment': 3}


## TF-IDF (Term Frequency - Inverse Term Frequency)

In [61]:
df = pd.DataFrame({
    "text": [
        "people watch shwatech",
        "shwatech watch shwatech",
        "people write comment",
        "shwatech write comment"
    ],
    "output": [
        1,
        1,
        0,
        0
    ]
})

df

text  output
0    people watch shwatech       1
1  shwatech watch shwatech       1
2     people write comment       0
3   shwatech write comment       0

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer

TF_IDF = TfidfVectorizer()

In [67]:
arr = TF_IDF.fit_transform(df['text']).toarray()

In [68]:
arr

array([[0.        , 0.61366674, 0.49681612, 0.61366674, 0.        ],
       [0.        , 0.        , 0.8508161 , 0.52546357, 0.        ],
       [0.57735027, 0.57735027, 0.        , 0.        , 0.57735027],
       [0.61366674, 0.        , 0.49681612, 0.        , 0.61366674]])

In [71]:
print(TF_IDF.idf_)

[1.51082562 1.51082562 1.22314355 1.51082562 1.51082562]
